name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Ensure tag is on master
        run: |
          git fetch origin master
          if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/master; then
            echo "Tag is not on master branch. Exiting."
            exit 1
          fi

      - uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
